#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_InzOpr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HistoriaOgladaniaDB")]
	public partial class BazaHistoriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabelaOgladane(TabelaOgladane instance);
    partial void UpdateTabelaOgladane(TabelaOgladane instance);
    partial void DeleteTabelaOgladane(TabelaOgladane instance);
    #endregion
		
		public BazaHistoriaDataContext() : 
				base(global::Projekt_InzOpr.Properties.Settings.Default.HistoriaOgladaniaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BazaHistoriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaHistoriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaHistoriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaHistoriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TabelaOgladane> TabelaOgladanes
		{
			get
			{
				return this.GetTable<TabelaOgladane>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TabelaOgladane")]
	public partial class TabelaOgladane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Sciezka;
		
		private string _Tytul;
		
		private int _CzasCalosci;
		
		private System.Nullable<double> _MomentZatrzymania;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSciezkaChanging(string value);
    partial void OnSciezkaChanged();
    partial void OnTytulChanging(string value);
    partial void OnTytulChanged();
    partial void OnCzasCalosciChanging(int value);
    partial void OnCzasCalosciChanged();
    partial void OnMomentZatrzymaniaChanging(System.Nullable<double> value);
    partial void OnMomentZatrzymaniaChanged();
    #endregion
		
		public TabelaOgladane()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sciezka", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Sciezka
		{
			get
			{
				return this._Sciezka;
			}
			set
			{
				if ((this._Sciezka != value))
				{
					this.OnSciezkaChanging(value);
					this.SendPropertyChanging();
					this._Sciezka = value;
					this.SendPropertyChanged("Sciezka");
					this.OnSciezkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tytul
		{
			get
			{
				return this._Tytul;
			}
			set
			{
				if ((this._Tytul != value))
				{
					this.OnTytulChanging(value);
					this.SendPropertyChanging();
					this._Tytul = value;
					this.SendPropertyChanged("Tytul");
					this.OnTytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzasCalosci", DbType="Int NOT NULL")]
		public int CzasCalosci
		{
			get
			{
				return this._CzasCalosci;
			}
			set
			{
				if ((this._CzasCalosci != value))
				{
					this.OnCzasCalosciChanging(value);
					this.SendPropertyChanging();
					this._CzasCalosci = value;
					this.SendPropertyChanged("CzasCalosci");
					this.OnCzasCalosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MomentZatrzymania", DbType="Float")]
		public System.Nullable<double> MomentZatrzymania
		{
			get
			{
				return this._MomentZatrzymania;
			}
			set
			{
				if ((this._MomentZatrzymania != value))
				{
					this.OnMomentZatrzymaniaChanging(value);
					this.SendPropertyChanging();
					this._MomentZatrzymania = value;
					this.SendPropertyChanged("MomentZatrzymania");
					this.OnMomentZatrzymaniaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
