#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_InzOpr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HistoriaOgladania")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertObejrzaneFilmy(ObejrzaneFilmy instance);
    partial void UpdateObejrzaneFilmy(ObejrzaneFilmy instance);
    partial void DeleteObejrzaneFilmy(ObejrzaneFilmy instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Projekt_InzOpr.Properties.Settings.Default.HistoriaOgladaniaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ObejrzaneFilmy> ObejrzaneFilmies
		{
			get
			{
				return this.GetTable<ObejrzaneFilmy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObejrzaneFilmy")]
	public partial class ObejrzaneFilmy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SciezkaDoPliku;
		
		private System.Nullable<double> _MomentZatrzymania;
		
		private string _Tytul;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSciezkaDoPlikuChanging(string value);
    partial void OnSciezkaDoPlikuChanged();
    partial void OnMomentZatrzymaniaChanging(System.Nullable<double> value);
    partial void OnMomentZatrzymaniaChanged();
    partial void OnTytulChanging(string value);
    partial void OnTytulChanged();
    #endregion
		
		public ObejrzaneFilmy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SciezkaDoPliku", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string SciezkaDoPliku
		{
			get
			{
				return this._SciezkaDoPliku;
			}
			set
			{
				if ((this._SciezkaDoPliku != value))
				{
					this.OnSciezkaDoPlikuChanging(value);
					this.SendPropertyChanging();
					this._SciezkaDoPliku = value;
					this.SendPropertyChanged("SciezkaDoPliku");
					this.OnSciezkaDoPlikuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MomentZatrzymania", DbType="float")]
		public System.Nullable<double> MomentZatrzymania
		{
			get
			{
				return this._MomentZatrzymania;
			}
			set
			{
				if ((this._MomentZatrzymania != value))
				{
					this.OnMomentZatrzymaniaChanging(value);
					this.SendPropertyChanging();
					this._MomentZatrzymania = value;
					this.SendPropertyChanged("MomentZatrzymania");
					this.OnMomentZatrzymaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tytul
		{
			get
			{
				return this._Tytul;
			}
			set
			{
				if ((this._Tytul != value))
				{
					this.OnTytulChanging(value);
					this.SendPropertyChanging();
					this._Tytul = value;
					this.SendPropertyChanged("Tytul");
					this.OnTytulChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
