#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_InzOpr
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SerwerHistoria")]
	public partial class HistoriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabela(Tabela instance);
    partial void UpdateTabela(Tabela instance);
    partial void DeleteTabela(Tabela instance);
    #endregion
		
		public HistoriaDataContext() : 
				base(global::Projekt_InzOpr.Properties.Settings.Default.SerwerHistoriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HistoriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tabela> Tabelas
		{
			get
			{
				return this.GetTable<Tabela>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabela")]
	public partial class Tabela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Tytul;
		
		private double _CzasCaly;
		
		private System.Nullable<double> _CzasZatrzymania;
		
		private string _Sciezka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTytulChanging(string value);
    partial void OnTytulChanged();
    partial void OnCzasCalyChanging(double value);
    partial void OnCzasCalyChanged();
    partial void OnCzasZatrzymaniaChanging(System.Nullable<double> value);
    partial void OnCzasZatrzymaniaChanged();
    partial void OnSciezkaChanging(string value);
    partial void OnSciezkaChanged();
    #endregion
		
		public Tabela()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tytul
		{
			get
			{
				return this._Tytul;
			}
			set
			{
				if ((this._Tytul != value))
				{
					this.OnTytulChanging(value);
					this.SendPropertyChanging();
					this._Tytul = value;
					this.SendPropertyChanged("Tytul");
					this.OnTytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzasCaly", DbType="Float NOT NULL")]
		public double CzasCaly
		{
			get
			{
				return this._CzasCaly;
			}
			set
			{
				if ((this._CzasCaly != value))
				{
					this.OnCzasCalyChanging(value);
					this.SendPropertyChanging();
					this._CzasCaly = value;
					this.SendPropertyChanged("CzasCaly");
					this.OnCzasCalyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CzasZatrzymania", DbType="Float")]
		public System.Nullable<double> CzasZatrzymania
		{
			get
			{
				return this._CzasZatrzymania;
			}
			set
			{
				if ((this._CzasZatrzymania != value))
				{
					this.OnCzasZatrzymaniaChanging(value);
					this.SendPropertyChanging();
					this._CzasZatrzymania = value;
					this.SendPropertyChanged("CzasZatrzymania");
					this.OnCzasZatrzymaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sciezka", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Sciezka
		{
			get
			{
				return this._Sciezka;
			}
			set
			{
				if ((this._Sciezka != value))
				{
					this.OnSciezkaChanging(value);
					this.SendPropertyChanging();
					this._Sciezka = value;
					this.SendPropertyChanged("Sciezka");
					this.OnSciezkaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
